version: '3.0'
services:
  web:
    image: litharts/coinpayments-magento2
    build: .
    expose:
      - "8081"
    links:
      - db
    env_file:
      - env
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env
volumes:
  db-data: