#!/usr/bin/env bash

su www-data <<EOSU
ln -s ~/.composer/auth.json /var/www/html/var/composer_home/
/var/www/html/bin/magento sampledata:deploy
/var/www/html/bin/magento setup:upgrade
chmod 777 -R /var/www/html/var
chmod 777 -R /var/www/html/pub
/var/www/html/bin/magento deploy:mode:set production
chmod 777 -R /var/www/html/var
chmod 777 -R /var/www/html/pub
/var/www/html/bin/magento c:c
EOSU